hospital app/main/default/objects/Consultant__c/Consultant__c.object-meta.xml
<CustomObject>
    <label>Consultant</label>
    <nameField>
        <label>Consultant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Consultants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hospital app/main/default/objects/New_Patient__c/New_Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

hospital app/main/default/objects/New_Patient__c/fields/Consultant__c.field-meta.xml
<CustomField>
    <fullName>Consultant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consultant</label>
    <referenceTo>Consultant__c</referenceTo>
    <relationshipName>New_Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/New_Patient__c/fields/Patient_Name__c.field-meta.xml
<CustomField>
    <fullName>Patient_Name__c</fullName>
    <formula>TEXT(Title__c) &amp; &quot; &quot; &amp;  Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patient Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/New_Patient__c/fields/Ref_By__c.field-meta.xml
<CustomField>
    <fullName>Ref_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ref. By</label>
    <referenceTo>Ref_By__c</referenceTo>
    <relationshipName>New_Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

hospital app/main/default/objects/New_Patient__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

hospital app/main/default/objects/Ref_By__c/Ref_By__c.object-meta.xml
<CustomObject>
    <label>Ref. By</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Refs. By</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/newPatient.cls
public with sharing class newPatient {
    @AuraEnabled
    public static List<New_Patient__c> searchPatientRecord(String toDate) {
        try {
            if (toDate != null) {
                Date dateToSearch = Date.valueOf(toDate);
                // Query only date part of the CreatedDate
                return [SELECT Id, Name, Patient_Name__c, Sex__c, Email_ID__c, Ref_By__r.Name, Consultant__c, Mobile_No__c, CreatedDate FROM New_Patient__c WHERE DAY_ONLY(CreatedDate) = :dateToSearch];
            } else {
                return null;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}